### ISSUE TITLE
This mod crashes on 1.14.4

### ISSUE THREAD

**Issue by Blayyke** [manmaed/Cookies#3]

**Comment by manmaed** [comment]
Forge Version is 1.12.2 
Fabric Version is 1.14

**Comment by Blayyke** [comment]
Yeah I was running it on fabric

**Comment by UnRealDinnerbone** [comment]
Can I get a crash report pls

**Comment by Blayyke** [comment]
https://paste.ee/p/ubW1a

**Comment by UnRealDinnerbone** [comment]
I will get and update out latter
